listener 883

allow_anonymous false
password_file /mosquitto/passwd.txt

persistence true
persistence_location /mosquitto/data/
autosave_interval 5

listener 9883
protocol http_api
http_dir /usr/share/mosquitto/dashboard
